### PR TITLE
Emotion recognition

### PR DESCRIPTION
**Pull request by Kozitsin**

### CODE REVIEW

**Comment by grib0ed0v** [comment]
@Kozitsin @maviko please provide short description of task, what has been implemented and so on.

**Comment by Kozitsin** [comment]
@grib0ed0v 
where it should be done? just readme.md - small paragraph about task?
cause' readme.md has already had detailed description of components.

**Comment by grib0ed0v** [comment]
@Kozitsin it was planned to add this info to this PR. 
So, now please add small section to readme.md and that's it.

**Comment by Kozitsin** [comment]
@grib0ed0v , validate again, please.

**Review by grib0ed0v — APPROVED** [review]

**Pull request merged**
